### HTTP Request to Get All Expenses
GET http://localhost:3000/movements

### HTTP Request to Create a New Expense
POST http://localhost:3000/movements
Content-Type: application/json

{
  "movement_type": "expense",
  "description": "Hello",
  "amount": "100",
  "date": "2026-05-12",
  "category_id": "ee5bb237-23f9-4b6b-aca6-9f8a13f1f9ae",
  "account_id": "ad09f676-af8a-4d81-ad15-c82ce6886088"
}

### HTTP Request to Delete an Expense
DELETE http://localhost:3000/movements/9e2e2503-d517-4034-966f-30e797d32856