### HTTP Request to Get All Expenses
GET http://localhost:3000/expenses

### HTTP Request to Create a New Expense
POST http://localhost:3000/expenses
Content-Type: application/json

{
  "amount": 150,
  "category_id": "66f3df4b-fa22-4569-9d60-8f863e90b7d7",
  "account_id": "ddb283dd-3a9f-4374-991d-59cd71438504",
  "date": "2024-06-01",
  "description": "transport expense"
}

### HTTP Request to Delete an Expense
DELETE http://localhost:3000/expenses/0791a50c-0972-439e-a8f9-ba87f0a3af9e