### HTTP Request to Get All Expenses
GET http://localhost:3000/expenses

### HTTP Request to Create a New Expense
POST http://localhost:3000/expenses
Content-Type: application/json

{
  "description": "Grocery shopping",
  "amount": 2500,
  "date": "2026-05-15",
  "category_id": "ca634af4-5e41-4456-89d8-ecc3cdcd8525",
  "account_id": "be0844fe-8dcc-4db7-8532-29e2c9f1543f"
}

### HTTP Request to Delete an Expense
DELETE http://localhost:3000/expenses/9e2e2503-d517-4034-966f-30e797d32856